[package]
name = "bots_handheld_controller"
version = "0.1.0"
edition = "2024"

[dependencies]
# bevy = "0.16.1"
bevy = { version = "0.16.1", default-features = false, features = ["x11"] }
bevy_gstreamer = "0.7.0"
